export const theme = {
  borderRadius: {
    default: '1.5rem',
    circle: '50%',
  },
  /* The colour names are generated by:
  https://chir.ag/projects/name-that-color */
  colour: {
    white: '#FFFFFF',
    softPeach: '#F9F2F4',
    pippin: '#FFE0E7',
    ceriseRed: '#DD3864',
    mantis: '#93C963',
    havelockBlue: '#5A90E0',
    fiord: '#3E4F6D',
  },
  font: {
    primary: 'Raleway, sans-serif',
  },
  fontSize: {
    default: '1.6rem',
    xxs: '1.2rem',
    xs: '1.4rem',
    sm: '1.5rem',
    md: '2rem',
    lg: '4.4rem',
    xl: '5rem',
  },
  fontWeight: {
    regular: '400',
    semiBold: '600',
    extraBold: '800',
  },
  lineHeight: {
    default: 1.6,
  },
  transition: {
    speed: {
      default: '300ms',
      fast: '100ms',
      medium: '1000ms',
      slow: '2000ms',
    },
  },
  breakpoints: {
    xl: 1440,
    lg: 992,
    md: 768,
    sm: 480,
  },
}
