const theme = {
  borderRadius: {
    default: '1.5rem',
    circle: '50%',
  },
  /* The colour names are generated by:
  https://chir.ag/projects/name-that-color */
  colour: {
    white: '#FFFFFF',
    softPeach: '#F9F2F4',
    pippin: '#FFE0E7',
    ceriseRed: '#DD3864',
    mantis: '#93C963',
    havelockBlue: '#5A90E0',
    fiord: '#3E4F6D',
  },
  font: {
    primary: 'Raleway, sans-serif',
  },
  fontSize: {
    default: 1.6,
  },
  fontWeight: {
    regular: '400',
    semiBold: '600',
    extraBold: '800',
  },
}

const themeBreakpoints = {
  breakpoints: {
    extraLarge: 1440,
    large: 992,
    medium: 768,
    small: 480,
  },
}

export { theme, themeBreakpoints }